import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";
import { terms } from "./models/terms.js";

export const TermSchema = createSelectSchema(terms);

// Base schema without autogenerated fields
const BaseCreateTermSchema = createInsertSchema(terms)
      .omit({
            id: true,
            createdAt: true,
            updatedAt: true,
      })
      .extend({
            name: z.string().trim().min(1).max(20),
            startDate: z.coerce.date(),
            endDate: z.coerce.date(),
            isCurrent: z.boolean().optional(),
      });

const termDateRule = <T extends { startDate?: Date; endDate?: Date }>(
      data: T,
      ctx: z.RefinementCtx,
) => {
      if (data.startDate && data.endDate && data.endDate < data.startDate) {
            ctx.addIssue({
                  code: "custom",
                  message: "endDate must not be earlier than startDate",
                  path: ["endDate"],
            });
      }
};

export const CreateTermSchema = BaseCreateTermSchema.superRefine(termDateRule);
export const UpdateTermSchema = BaseCreateTermSchema.partial().superRefine(termDateRule);

export type Term = z.infer<typeof TermSchema>;
export type CreateTermDTO = z.infer<typeof CreateTermSchema>;
export type UpdateTermDTO = z.infer<typeof UpdateTermSchema>;
